server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/playground
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true

